#!/bin/bash
set -e

# Install Python dependencies
pip3 install -r /var/www/proftpd_flask/requirements.txt

# Set up the database
cd /var/www/proftpd_flask
flask db upgrade

# Make the script executable
chmod +x /usr/local/bin/run_proftpd_flask

exit 0
